//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedbackService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFeedback
    {
        public long id { get; set; }
        public long userId { get; set; }
        public long commentId { get; set; }
        public Nullable<bool> isLiked { get; set; }
        public Nullable<bool> isDisliked { get; set; }
    }
}
