//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedbackService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPost
    {
        public long id { get; set; }
        public string post { get; set; }
        public Nullable<System.DateTime> created { get; set; }
    }
}
